/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author William
 */
public class FrmMenu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPaneMenu;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        this.setLayout(null);
        jDesktopPaneMenu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPaneMenu.setBounds(0, 0, ancho, (alto - 100));
        this.add(jDesktopPaneMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_NuevoUsuario = new javax.swing.JMenuItem();
        jMenu_GestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_NuevoProducto = new javax.swing.JMenuItem();
        jMenuItem_GestionarProducto = new javax.swing.JMenuItem();
        jMenuItem_ActualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_NuevoCliente = new javax.swing.JMenuItem();
        jMenuItem_GestionarCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_NuevaCategoria = new javax.swing.JMenuItem();
        jMenuItem_GestionarCategorias = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_NuevaVenta = new javax.swing.JMenuItem();
        jMenuItem_GestionarVentas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_ReporteClientes = new javax.swing.JMenuItem();
        jMenuItem_ReporteCategorias = new javax.swing.JMenuItem();
        jMenuItem_ReporteProductos = new javax.swing.JMenuItem();
        jMenuItem_ReporteVentas = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_VerHistorial = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem_Salir = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_NuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_NuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem_NuevoUsuario.setText("Nuevo Usuario");
        jMenuItem_NuevoUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_NuevoUsuario);

        jMenu_GestionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu_GestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenu_GestionarUsuario.setText("Gestionar Usuarios");
        jMenu_GestionarUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu_GestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_GestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu_GestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_NuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_NuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem_NuevoProducto.setText("Nuevo Producto");
        jMenuItem_NuevoProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_NuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_NuevoProducto);

        jMenuItem_GestionarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_GestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenuItem_GestionarProducto.setText("Gestionar Productos");
        jMenuItem_GestionarProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu2.add(jMenuItem_GestionarProducto);

        jMenuItem_ActualizarStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_ActualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem_ActualizarStock.setText("Actualizar Stock");
        jMenuItem_ActualizarStock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu2.add(jMenuItem_ActualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_NuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_NuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem_NuevoCliente.setText("Nuevo Cliente");
        jMenuItem_NuevoCliente.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_NuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_NuevoCliente);

        jMenuItem_GestionarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_GestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem_GestionarCliente.setText("Gestionar Cliente");
        jMenuItem_GestionarCliente.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(jMenuItem_GestionarCliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu4.setText("Categoría");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_NuevaCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_NuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem_NuevaCategoria.setText("Nueva Categoría");
        jMenuItem_NuevaCategoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_NuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_NuevaCategoria);

        jMenuItem_GestionarCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_GestionarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem_GestionarCategorias.setText("Gestionar Categorias");
        jMenu4.add(jMenuItem_GestionarCategorias);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu6.setText("Facturar");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_NuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_NuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem_NuevaVenta.setText("Nueva Venta");
        jMenuItem_NuevaVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(jMenuItem_NuevaVenta);

        jMenuItem_GestionarVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_GestionarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem_GestionarVentas.setText("Gestionar Ventas");
        jMenuItem_GestionarVentas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(jMenuItem_GestionarVentas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu7.setText("Reportes");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_ReporteClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_ReporteClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_ReporteClientes.setText("Clientes");
        jMenuItem_ReporteClientes.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu7.add(jMenuItem_ReporteClientes);

        jMenuItem_ReporteCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_ReporteCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_ReporteCategorias.setText("Categorías");
        jMenuItem_ReporteCategorias.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu7.add(jMenuItem_ReporteCategorias);

        jMenuItem_ReporteProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_ReporteProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_ReporteProductos.setText("Productos");
        jMenuItem_ReporteProductos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu7.add(jMenuItem_ReporteProductos);

        jMenuItem_ReporteVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_ReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem_ReporteVentas.setText("Ventas");
        jMenuItem_ReporteVentas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu7.add(jMenuItem_ReporteVentas);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu8.setText("Historial");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_VerHistorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_VerHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenuItem_VerHistorial.setText("Ver Historial");
        jMenuItem_VerHistorial.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu8.add(jMenuItem_VerHistorial);

        jMenuBar1.add(jMenu8);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu11.setText("Cerrar Sesión");
        jMenu11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu11.setPreferredSize(new java.awt.Dimension(200, 30));

        jMenuItem_Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenuItem_Salir.setText("Salir");
        jMenuItem_Salir.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu11.add(jMenuItem_Salir);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_NuevoUsuarioActionPerformed

    private void jMenu_GestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_GestionarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_GestionarUsuarioActionPerformed

    private void jMenuItem_NuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevaCategoriaActionPerformed
        InterCategoria intercategoria = new InterCategoria(); //Revisar si dice "cannot find symbol"
        jDesktopPaneMenu.add(intercategoria);
        intercategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevaCategoriaActionPerformed

    private void jMenuItem_NuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoProductoActionPerformed
        InterProducto InterProducto = new InterProducto(); //Revisar si dice "cannot find symbol"
        jDesktopPaneMenu.add(InterProducto);
        InterProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevoProductoActionPerformed

    private void jMenuItem_NuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NuevoClienteActionPerformed
        InterCliente InterCliente = new InterCliente(); //Revisar si dice "cannot find symbol"
        jDesktopPaneMenu.add(InterCliente);
        InterCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_NuevoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem_ActualizarStock;
    private javax.swing.JMenuItem jMenuItem_GestionarCategorias;
    private javax.swing.JMenuItem jMenuItem_GestionarCliente;
    private javax.swing.JMenuItem jMenuItem_GestionarProducto;
    private javax.swing.JMenuItem jMenuItem_GestionarVentas;
    private javax.swing.JMenuItem jMenuItem_NuevaCategoria;
    private javax.swing.JMenuItem jMenuItem_NuevaVenta;
    private javax.swing.JMenuItem jMenuItem_NuevoCliente;
    private javax.swing.JMenuItem jMenuItem_NuevoProducto;
    private javax.swing.JMenuItem jMenuItem_NuevoUsuario;
    private javax.swing.JMenuItem jMenuItem_ReporteCategorias;
    private javax.swing.JMenuItem jMenuItem_ReporteClientes;
    private javax.swing.JMenuItem jMenuItem_ReporteProductos;
    private javax.swing.JMenuItem jMenuItem_ReporteVentas;
    private javax.swing.JMenuItem jMenuItem_Salir;
    private javax.swing.JMenuItem jMenuItem_VerHistorial;
    private javax.swing.JMenuItem jMenu_GestionarUsuario;
    // End of variables declaration//GEN-END:variables
}
